"""initial schema

Revision ID: 7092a21fd55a
Revises: 
Create Date: 2026-02-14 00:59:52.931232
"""
from alembic import op
import sqlalchemy as sa


revision = '7092a21fd55a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exercise_type', sa.Enum('duration', 'sets_reps', 'both', name='exercise_type'), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('devadmin', 'professional', 'patient', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='appointment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_appointments_patient_scheduled', ['patient_id', 'scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_professional_id'), ['professional_id'], unique=False)

    op.create_table('exercise_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exercise_type', sa.Enum('duration', 'sets_reps', 'both', name='exercise_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='request_status'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_exercise_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_requests_requested_by'), ['requested_by'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period', sa.Enum('weekly', 'monthly', 'yearly', name='goal_period'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_goals_patient_period', ['patient_id', 'period'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index('ix_meals_patient_eaten', ['patient_id', 'eaten_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meals_patient_id'), ['patient_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_author_id'), ['author_id'], unique=False)

    op.create_table('professional_patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('professional_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id', 'patient_id', name='uq_professional_patient')
    )
    with op.batch_alter_table('professional_patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professional_patients_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professional_patients_professional_id'), ['professional_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('avatar_storage_key', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weigh_ins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weigh_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weigh_ins_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_weigh_ins_patient_recorded', ['patient_id', 'recorded_at'], unique=False)

    op.create_table('workouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_workouts_patient_started', ['patient_id', 'started_at'], unique=False)

    op.create_table('meal_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meal_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_photos_meal_id'), ['meal_id'], unique=False)

    op.create_table('notification_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'patient_id', name='uq_notification_recipient')
    )
    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.create_index('ix_notif_recip_patient_read', ['patient_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipients_notification_id'), ['notification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipients_patient_id'), ['patient_id'], unique=False)

    op.create_table('workout_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_items_workout_id'), ['workout_id'], unique=False)

    op.create_table('workout_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workout_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_photos_workout_id'), ['workout_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_photos_workout_id'))

    op.drop_table('workout_photos')
    with op.batch_alter_table('workout_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_items_workout_id'))

    op.drop_table('workout_items')
    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_recipients_patient_id'))
        batch_op.drop_index(batch_op.f('ix_notification_recipients_notification_id'))
        batch_op.drop_index('ix_notif_recip_patient_read')

    op.drop_table('notification_recipients')
    with op.batch_alter_table('meal_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_photos_meal_id'))

    op.drop_table('meal_photos')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index('ix_workouts_patient_started')
        batch_op.drop_index(batch_op.f('ix_workouts_patient_id'))

    op.drop_table('workouts')
    with op.batch_alter_table('weigh_ins', schema=None) as batch_op:
        batch_op.drop_index('ix_weigh_ins_patient_recorded')
        batch_op.drop_index(batch_op.f('ix_weigh_ins_patient_id'))

    op.drop_table('weigh_ins')
    op.drop_table('profiles')
    with op.batch_alter_table('professional_patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professional_patients_professional_id'))
        batch_op.drop_index(batch_op.f('ix_professional_patients_patient_id'))

    op.drop_table('professional_patients')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_author_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_patient_id'))
        batch_op.drop_index('ix_meals_patient_eaten')

    op.drop_table('meals')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_patient_period')
        batch_op.drop_index(batch_op.f('ix_goals_patient_id'))

    op.drop_table('goals')
    with op.batch_alter_table('exercise_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_requests_requested_by'))

    op.drop_table('exercise_requests')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_professional_id'))
        batch_op.drop_index('ix_appointments_patient_scheduled')
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
