"""Add meal comments and patient invitations tables

Revision ID: c61456329be3
Revises: b3f1a2c8d9e0
Create Date: 2026-02-14 20:20:40.763738
"""
from alembic import op
import sqlalchemy as sa


revision = 'c61456329be3'
down_revision = 'b3f1a2c8d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_comments',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('meal_id', sa.String(36), nullable=False),
    sa.Column('professional_id', sa.String(36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_comments', schema=None) as batch_op:
        batch_op.create_index('ix_meal_comments_meal_created', ['meal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_comments_meal_id'), ['meal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_comments_professional_id'), ['professional_id'], unique=False)

    op.create_table('patient_invitations',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('professional_id', sa.String(36), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='invitation_status'), nullable=False),
    sa.Column('notification_id', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_invitations', schema=None) as batch_op:
        batch_op.create_index('ix_patient_inv_email_status', ['patient_email', 'status'], unique=False)
        batch_op.create_index('ix_patient_inv_prof_status', ['professional_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_invitations_patient_email'), ['patient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_invitations_professional_id'), ['professional_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_invitations_professional_id'))
        batch_op.drop_index(batch_op.f('ix_patient_invitations_patient_email'))
        batch_op.drop_index('ix_patient_inv_prof_status')
        batch_op.drop_index('ix_patient_inv_email_status')

    op.drop_table('patient_invitations')
    with op.batch_alter_table('meal_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_comments_professional_id'))
        batch_op.drop_index(batch_op.f('ix_meal_comments_meal_id'))
        batch_op.drop_index('ix_meal_comments_meal_created')

    op.drop_table('meal_comments')
    # ### end Alembic commands ###
