"""add unique constraint on profile phone

Revision ID: ea73dc6a59d0
Revises: 7092a21fd55a
Create Date: 2026-02-14 15:50:46.144500
"""
from alembic import op
import sqlalchemy as sa


revision = 'ea73dc6a59d0'
down_revision = '7092a21fd55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
